### ISSUE TITLE
Making feature branches, pull requesting, and approving yourself is a lot of work.

### ISSUE THREAD

**Issue by edenfrosst** [choltfo/RTSGame#4]
And it bugs the few of us who are still subscribed to updates on this repo 👍

**Comment by Charles-Isaac** [comment]
I totally agree

**Comment by Charles-Isaac** [comment]
This seems to have solved the issue: 
Tip before merging: do git pull choltfo master to get up-to-date with main branch.

Thanks Ian.

**Comment by edenfrosst** [comment]
:heart: any time
